// <auto-generated />
namespace Imagine.BookManager.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Add_StudenAllocation_ExpiryData_Lucas : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Add_StudenAllocation_ExpiryData_Lucas));
        
        string IMigrationMetadata.Id
        {
            get { return "201712270836358_Add_StudenAllocation_ExpiryData_Lucas"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
