// <auto-generated />
namespace Imagine.BookManager.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class brian : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(brian));
        
        string IMigrationMetadata.Id
        {
            get { return "201712111146463_brian"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
